version: '3.9'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data_glauco_filho:/root/.pgadmin
    restart: always

volumes:
  pgadmin_data_glauco_filho:
